spring.application.name=ScopeProject

server.port=8080
server.address=0.0.0.0

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/scopeindia
spring.datasource.username=root
spring.datasource.password=

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mail Sending
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=829a30d46ae1b4
spring.mail.password=cb2c9f6206df7d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true